### ISSUE TITLE
Dynamically Add Meta Tags Based on Tournament Title

### ISSUE THREAD

**Issue by akshay-waghmare** [akiaksdon/laundry-app#45]
### Summary
We need to dynamically update the page title and meta tags (description, keywords, etc.) based on the match the user clicks on in the `HomeComponent` of our Angular app. This will enhance our app's SEO and improve social media sharing for specific match pages.

### Context
In the `HomeComponent`, we display a list of live matches. When a user clicks on a match, we should update the meta tags dynamically for that specific match before navigating to the match details page. This will ensure that the meta tags and page title reflect the match the user is interacting with.

### Tasks
1. **Import necessary services:**
   - Import `Title` and `Meta` from `@angular/platform-browser` in `home.component.ts` to manage dynamic meta tags.

   ```typescript
   import { Meta, Title } from '@angular/platform-browser';
   ```

2. **Inject `Meta` and `Title` services in the constructor:**
   
   ```typescript
   constructor(
     private eventListService: EventListService,
     private router: Router,
     private metaService: Meta, 
     private titleService: Title 
   ) { }
   ```

3. **Update `navigateToMatch` function to dynamically set meta tags:**

   Modify the `navigateToMatch` function to update meta tags dynamically when the user clicks on a match:

   ```typescript
   navigateToMatch(match: any): void {
     // Dynamically update meta tags for the clicked match
     this.updateMetaTags(match);

     // Navigate to the match details page
     this.router.navigate(['cric-live', match.matchUrl]);
   }

   updateMetaTags(match: any): void {
     this.titleService.setTitle(match.title);  // Update page title dynamically
     this.metaService.updateTag({ name: 'description', content: match.description });  // Update meta description
     this.metaService.updateTag({ name: 'keywords', content: `${match.team1}, ${match.team2}, cricket match, live score, ${match.title}` });  // Update meta keywords
     this.metaService.updateTag({ property: 'og:title', content: match.title });  // Open Graph title
     this.metaService.updateTag({ property: 'og:description', content: match.description });  // Open Graph description
   }
   ```

4. **Meta tags to be updated:**
   - `title`: Set dynamically based on the clicked match.
   - `description`: Use match details to create a relevant description.
   - `keywords`: Use team names and match data to create targeted keywords.
   - `og:title` and `og:description`: Set Open Graph tags for better social media sharing.

### Acceptance Criteria
- [ ] The page title and meta tags should be dynamically updated when the user clicks on a specific match.
- [ ] Meta tags should reflect the match title, description, keywords, and Open Graph details.
- [ ] The updated meta tags should appear in the browser's DevTools.
- [ ] Ensure proper navigation to the match details page after updating the meta tags.

### Additional Information
This change will improve the SEO performance of match pages and enhance social sharing on platforms like Facebook and Twitter, where Open Graph tags are used.
